navbar:
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - {
        key: "about",
        link: "/about/",
        icon: "iconfont icon-user-fill",
        name: "About Me",
      }
